# Generated by Django 3.0.5 on 2020-04-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Category'),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftpost',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
    ]
