# Generated by Django 3.0.5 on 2020-04-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20200425_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ss',
        ),
    ]
