# Generated by Django 3.0.5 on 2020-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_remove_category_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='DraftPost',
        ),
    ]
